name: Auto Build Lichee RV Debian Linux Bootable Image.
on:
  push:
jobs:
  build-all-os:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Install depends
          run: sudo apt install -y qemu-user-static qemu-system qemu-utils qemu-system-misc binfmt-support

        - name: Prepare
          run: |
            echo ${{runner.workspace}}
            mkdir -p lichee_rv_dock
        - name: Build
          run: |
            docker-compose build

        - name: Create Lichee RV Dock Image
          run: |
            docker-compose up dock
            ls -l lichee_rv_dock/*

        - name: Upload image
          uses: actions/upload-artifact@v3
          with:
            path: lichee_rv_dock/lichee_rv_dock*.img.xz
